sudo: required
language: go
go:
- 1.7
before_install:
- sudo apt-get install zip
- go get github.com/tools/godep
- go get -d github.com/stretchr/testify/assert
install:
- godep restore
script:
- go test -v ./...
- mkdir linux_amd64
- mkdir windows_amd64
- go build  -o ./linux_amd64/blobporter github.com/Azure/blobporter
- export GOOS=windows
- go build  -o ./windows_amd64/BlobPorter.exe github.com/Azure/blobporter
- md5sum ./linux_amd64/blobporter > ./linux_amd64/blobporter.md5
- md5sum ./windows_amd64/BlobPorter.exe > ./windows_amd64/BlobPorter.exe.md5
- tar cvzf bp_linux.tar.gz linux_amd64
- zip bp_windows.zip ./windows_amd64/*
- bash inttest.sh inttest
deploy:
  provider: releases
  api_key:
    secure: KA60/HnH/QXUTssLzTqRhhxlxiJKVUhde247u95C90r81Rqi8OtCCdgi/Y5u37WXqiq8+11J0OD9/QRzQlSmZ0csFLlzxyTCQ+ea8hjb5GmEB9w9hWHh0IsL83VzSCpYcYJC4HlRCVjLLpqFzaeP1mkhObEnzFm70NHi/SVh1/LsxoJjtKViI7oA/id41UDZhL4dO9U8nYc3pIwsa+8+0OX3EQN4BAV4NHPWVxG3hT9RoODfh+ZRKapqV7iyi0ezDZUepWt9GqJI0S5R89m7w3Vz43qILEc8Dw2w2VTj4yQ0yz5PUXnPi9QYZ3IIP+F6DdjklbIi8m/Vpw1RQdsGYFPHfqUj0kKyb+RQoFD/MmxkxYRITYEmhR05uI8apE5D+T2YP4Aa7P/REt8DOFdh1O8qabeosRpl/KaGBzhjAjefo3A5GJTmPRfKUNh0LxgJeHlAu4XQov17+WEENf4LkvvbWuNAmZyA8UJYMt79PgFVyytlGE4MnNCMjHqidEFver160kg9Ma2zBO/18u/MDplNVpFMxUlJYK9f1vVm/5sfuNt24wP4Bi8h9nZykSbJeJ/v/TMZKqO0ImD6YLrgSOfuiVekue721N1y4BWONtLrp5CN6MA0WTWZBuJ3QI1UYN7XDBeIAlHuh+gYhghzsyiW5lUhWja7qfC4873YTa0=
file: 
    - bp_linux.tar.gz
    - bp_windows.zip
  on:
    repo: Azure/blobporter
    tags: true 